const assert = require('assert');
const RoomManager = require('../src/logic/RoomManager');
class FakeSocket { constructor(id){this.id=id;this.events=[];this.joined=new Set();this.disconnected=false;} join(room){this.joined.add(room);} emit(event,payload){this.events.push({event,payload});} disconnect(){this.disconnected=true;} last(event){return [...this.events].reverse().find(item=>item.event===event);} }
function makeIo(){return{ sockets:{sockets:new Map()}, to(){return{emit(){}};} };}
function addPlayer(manager,socket,name,roomId){manager.io.sockets.sockets.set(socket.id,socket);const result=roomId?manager.joinRoom(socket,roomId,name):manager.createRoom(socket,name);assert.equal(result.res?result.res.success:result.success,true);return result;}
function getSession(socket){return socket.last('session:issued')?.payload?.sessionId;}
function getPlayerId(manager,socket){return manager.getPlayerIdBySocket(socket.id);}
function setupGame(){const io=makeIo(),manager=new RoomManager(io),sockets=Array.from({length:6},(_,i)=>new FakeSocket(`socket-${i+1}`));addPlayer(manager,sockets[0],'Игрок 1');const roomId=manager.getRoomBySocket(sockets[0].id).roomId;sockets.slice(1).forEach((socket,index)=>addPlayer(manager,socket,`Игрок ${index+2}`,roomId));const room=manager.getRoomBySocket(sockets[0].id),ids=sockets.map(socket=>getPlayerId(manager,socket));assert.equal(room.startGame(ids[0]).success,true);return{io,manager,sockets,room,ids,sessions:sockets.map(getSession)};}

// 1. lobby disconnect/reconnect preserves the same player entity.
{const io=makeIo(),manager=new RoomManager(io),a=new FakeSocket('a');addPlayer(manager,a,'Alice');const room=manager.getRoomBySocket(a.id),playerId=getPlayerId(manager,a),token=getSession(a);manager.handleDisconnect(a.id);const b=new FakeSocket('b');io.sockets.sockets.set(b.id,b);const result=manager.reconnect(b,token);assert.equal(result.success,true);assert.equal(result.playerId,playerId);assert.ok(room.players.has(playerId));}
// 2. discussion reconnect keeps the player and current phase.
{const{io,manager,sockets,room,ids,sessions}=setupGame();room.status='DISCUSSION';room.timeLeft=99;const playerId=ids[2];manager.handleDisconnect(sockets[2].id);const b=new FakeSocket('discussion-reconnect');io.sockets.sockets.set(b.id,b);assert.equal(manager.reconnect(b,sessions[2]).success,true);assert.equal(room.status,'DISCUSSION');assert.equal(manager.getPlayerIdBySocket(b.id),playerId);}
// 3. voting preserves an existing vote across disconnect/reconnect.
{const{io,manager,sockets,room,ids,sessions}=setupGame();room.status='VOTING';room.votes.set(ids[0],ids[1]);manager.handleDisconnect(sockets[0].id);const b=new FakeSocket('voter-reconnect');io.sockets.sockets.set(b.id,b);manager.reconnect(b,sessions[0]);assert.equal(room.votes.get(ids[0]),ids[1]);}
// 4. defense keeps the candidate/speaker identity across reconnect.
{const{io,manager,sockets,room,ids,sessions}=setupGame();room.status='DEFENSE';room.isDefensePhase=true;room.defenseSpeakerId=ids[3];room.tiedCandidates=[ids[3],ids[4]];manager.handleDisconnect(sockets[3].id);const b=new FakeSocket('defense-reconnect');io.sockets.sockets.set(b.id,b);manager.reconnect(b,sessions[3]);assert.equal(room.defenseSpeakerId,ids[3]);assert.deepEqual(room.tiedCandidates,[ids[3],ids[4]]);}
// 5. eliminated players reconnect only as the same eliminated entity.
{const{io,manager,sockets,room,ids,sessions}=setupGame();room.players.get(ids[1]).eliminated=true;manager.handleDisconnect(sockets[1].id);const b=new FakeSocket('eliminated-reconnect');io.sockets.sockets.set(b.id,b);manager.reconnect(b,sessions[1]);assert.equal(room.players.get(ids[1]).eliminated,true);assert.equal(room.getSanitizedState(ids[1]).players.find(p=>p.id===ids[1]).eliminated,true);}
// 6. traitor identity is preserved and hidden from other players.
{const{io,manager,sockets,room,ids,sessions}=setupGame();const traitorId=room.traitorId,index=ids.indexOf(traitorId);assert.ok(index>=0);manager.handleDisconnect(sockets[index].id);const b=new FakeSocket('traitor-reconnect');io.sockets.sockets.set(b.id,b);manager.reconnect(b,sessions[index]);const own=room.getSanitizedState(traitorId).players.find(p=>p.id===traitorId),otherId=ids.find(id=>id!==traitorId),other=room.getSanitizedState(otherId).players.find(p=>p.id===traitorId);assert.equal(own.isTraitor,true);assert.equal(other.isTraitor,false);assert.equal(room.traitorId,traitorId);}
// 7. alliance/trust state is not tied to socket.id.
{const{io,manager,sockets,room,ids,sessions}=setupGame();room.status='DISCUSSION';room.proposeAlliance(ids[0],ids[1]);room.acceptAlliance(ids[1],ids[0]);room.updateTrust(ids[0],ids[1],1);const before=room.getMechanics().relations.get(ids[0]).get(ids[1]);manager.handleDisconnect(sockets[0].id);const b=new FakeSocket('alliance-reconnect');io.sockets.sockets.set(b.id,b);manager.reconnect(b,sessions[0]);assert.equal(room.getMechanics().relations.get(ids[0]).get(ids[1]),before);assert.equal(room.getMechanics().alliances.size,1);}
// 8. session token maps to its own player only; playerId is never client-selected.
{const{io,manager,sockets,ids,sessions}=setupGame();manager.handleDisconnect(sockets[0].id);const attacker=new FakeSocket('attacker');io.sockets.sockets.set(attacker.id,attacker);const result=manager.reconnect(attacker,sessions[1]);assert.equal(result.success,true);assert.equal(result.playerId,ids[1]);assert.notEqual(result.playerId,ids[0]);assert.equal(manager.getPlayerIdBySocket(attacker.id),ids[1]);}
// 9. duplicate active session performs a handoff.
{const{io,manager,sockets,ids,sessions}=setupGame();const second=new FakeSocket('duplicate');io.sockets.sockets.set(second.id,second);manager.reconnect(second,sessions[0]);assert.equal(manager.getPlayerIdBySocket(second.id),ids[0]);assert.equal(sockets[0].disconnected,true);assert.equal(manager.playerSocketMap.get(ids[0]),second.id);}
// 10. expired session permanently removes the player.
{const{manager,sockets,room,ids,sessions}=setupGame();manager.handleDisconnect(sockets[0].id);assert.equal(manager.expireSession(sessions[0]),true);assert.equal(room.players.has(ids[0]),false);assert.equal(manager.findSession(sessions[0]),null);}
// 11. host disconnect follows host-transfer; reconnect does not silently reclaim host.
{const{io,manager,sockets,room,ids,sessions}=setupGame();const oldHost=room.hostId;manager.handleDisconnect(sockets[0].id);assert.notEqual(room.hostId,oldHost);const newHost=room.hostId;assert.ok(newHost);const b=new FakeSocket('old-host-reconnect');io.sockets.sockets.set(b.id,b);manager.reconnect(b,sessions[0]);assert.equal(room.hostId,newHost);assert.equal(room.players.get(ids[0]).isHost,false);}
// 12. revote state remains intact during a disconnect.
{const{io,manager,sockets,room,ids,sessions}=setupGame();room.status='VOTING';room.isRevote=true;room.tiedCandidates=[ids[2],ids[3]];room.votes.set(ids[0],ids[2]);manager.handleDisconnect(sockets[0].id);const b=new FakeSocket('revote-reconnect');io.sockets.sockets.set(b.id,b);manager.reconnect(b,sessions[0]);assert.equal(room.isRevote,true);assert.deepEqual(room.tiedCandidates,[ids[2],ids[3]]);assert.equal(room.votes.get(ids[0]),ids[2]);}
// 13. GAME_OVER does not restore an active session.
{const{io,manager,sockets,room,sessions}=setupGame();room.status='GAME_OVER';manager.handleDisconnect(sockets[0].id);const b=new FakeSocket('after-game-over');io.sockets.sockets.set(b.id,b);const result=manager.reconnect(b,sessions[0]);assert.equal(result.success,false);assert.equal(result.code,'SESSION_EXPIRED');}
console.log('Reconnect/session recovery tests passed.');
